### ISSUE TITLE
exceeding `task_max_timeout` appears to crash scriptworker

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#128]
```
2017-07-11T18:56:52    DEBUG - waiting 300 seconds before reclaiming...
2017-07-11T19:00:06  WARNING - Exceeded timeout of 1800 seconds: 20167
Exception in callback max_timeout(<scriptworker...x7fdbd97aa5f8>, <Process 20167>, 1800) at /builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py:234
handle: <TimerHandle when=4875.318810819001 max_timeout(<scriptworker...x7fdbd97aa5f8>, <Process 20167>, 1800) at /builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py:234>
Traceback (most recent call last):
  File "/tools/python35/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py", line 256, in max_timeout
    asyncio.ensure_future(kill(pid))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 340, in run_forever
    raise RuntimeError('Event loop is running.')
RuntimeError: Event loop is running.
2017-07-11T19:00:22     INFO - exit code: -15
2017-07-11T19:00:37    DEBUG - "/builds/scriptworker/artifacts/public/chainOfTrust.json.asc" is encoded with "None" and has mime/type "text/plain"
2017-07-11T19:00:37     INFO - "/builds/scriptworker/artifacts/public/chainOfTrust.json.asc" can be gzip'd. Compressing...
2017-07-11T19:00:38     INFO - "/builds/scriptworker/artifacts/public/chainOfTrust.json.asc" compressed
2017-07-11T19:00:38    DEBUG - "/builds/scriptworker/artifacts/public/logs/chain_of_trust.log" is encoded with "None" and has mime/type "text/plain"
2017-07-11T19:00:38     INFO - "/builds/scriptworker/artifacts/public/logs/chain_of_trust.log" can be gzip'd. Compressing...
2017-07-11T19:00:38     INFO - "/builds/scriptworker/artifacts/public/logs/chain_of_trust.log" compressed
2017-07-11T19:00:38    DEBUG - "/builds/scriptworker/artifacts/public/logs/live_backing.log" is encoded with "None" and has mime/type "text/plain"
2017-07-11T19:00:38     INFO - "/builds/scriptworker/artifacts/public/logs/live_backing.log" can be gzip'd. Compressing...
2017-07-11T19:00:38     INFO - "/builds/scriptworker/artifacts/public/logs/live_backing.log" compressed
2017-07-11T19:00:38 CRITICAL - Fatal exception
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 112, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 385, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
Traceback (most recent call last):
  File "/builds/scriptworker/bin/scriptworker", line 9, in <module>
    load_entry_point('scriptworker==4.1.2', 'console_scripts', 'scriptworker')()
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 112, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 385, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
2017-07-11T19:02:19     INFO - Scriptworker starting up at 2017-07-11
```

**Comment by nthomas-mozilla** [comment]
We hit this with a long running signing job so still a live issue.
