### ISSUE TITLE
CoT verification didn't retry download on 503

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/scriptworker#175]
https://public-artifacts.taskcluster.net/RstI-tFwSBGepENskj7RMw/0/public/logs/chain_of_trust.log failed with a 503 downloading one of the artifacts, this is something that should be retried for, but there's no indication that it did so. Relevant output:

```
2018-01-09T17:13:25    DEBUG -  Verifying public/build/bn-BD/target.dmg is in IIrmueBbT3W4T2LH5ljPdg cot artifacts...
2018-01-09T17:13:25     INFO - Downloading Chain of Trust artifact:
https://queue.taskcluster.net/v1/task/IIrmueBbT3W4T2LH5ljPdg/artifacts/public/build/bn-BD/target.dmg
2018-01-09T17:16:55 CRITICAL - Chain of Trust verification error!
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/cot/verify.py", line 1563, in verify_chain_of_trust
    await download_cot_artifacts(chain)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/cot/verify.py", line 775, in download_cot_artifacts
    mandatory_artifacts_paths = await raise_future_exceptions(mandatory_artifact_tasks)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 319, in raise_future_exceptions
    succeeded_results, _ = await _process_future_exceptions(tasks, raise_at_first_error=True)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 354, in _process_future_exceptions
    raise exc
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/cot/verify.py", line 730, in download_cot_artifact
    chain.context, [url], parent_dir=link.cot_dir, valid_artifact_task_ids=[task_id]
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/artifacts.py", line 317, in download_artifacts
    await raise_future_exceptions(tasks)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 319, in raise_future_exceptions
    succeeded_results, _ = await _process_future_exceptions(tasks, raise_at_first_error=True)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 354, in _process_future_exceptions
    raise exc
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 252, in retry_async
    return await func(*args, **kwargs)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 470, in download_file
    raise DownloadError("{} status {} is not 200!".format(url, resp.status))
scriptworker.exceptions.DownloadError: https://queue.taskcluster.net/v1/task/IIrmueBbT3W4T2LH5ljPdg/artifacts/public/build/bn-BD/target.dmg status 503 is not 200!
```

**Comment by escapewindow** [comment]
Hm, `retry_async` works:

```python
#!/usr/bin/env python

import asyncio
import logging
from scriptworker.exceptions import DownloadError
from scriptworker.utils import retry_async

logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

count = [0]

async def foo():
    count[0] += 1
    log.info(count[0])
    if count[0] < 2:
        raise DownloadError("foo")
    log.info("YAY")
    return "yay"


def callback(*args, **kwargs):
    return .1

loop = asyncio.get_event_loop()
loop.run_until_complete(
    retry_async(
        foo, retry_exceptions=(DownloadError, ),
        sleeptime_callback=callback
    )
)
```

By default `retry_exceptions` is `(Exception, )` which is overly broad, but it shouldn't break here. I can try making the exception list more restrictive and explicit.

**Comment by escapewindow** [comment]
12:10 <•catlee> I think we are retrying that cot download, but the async_retry debug logs aren't shown
12:11 <•catlee> there's a long time between the last two lines
12:12 <aki> catlee: i was hoping that, because i'm not seeing where it's not rerunning in the code
12:12 <aki> so we'll just live with this, or adjust retry count / backoff timing
