### ISSUE TITLE
scriptworker doesn't put task in exception on all Exception raised during cot_verify

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#215]
## Symptoms

* When the error shown in the logs is raised, scriptworker doesn't release the task and resolve it in exception. Thus, the queue still shows it as taken until `claim-expired` is raised.
* Because the task is `claim-expired`, no logs are attached to the task. The logs below have been gotten from `worker.log` on the machine.

```
2018-05-04T11:41:43    DEBUG - Calling claimWork...
2018-05-04T11:41:45    DEBUG - Writing task file to /builds/scriptworker/work/task.json...
2018-05-04T11:41:45     INFO - Going to run taskId MTp5zddYQOGnoxBdnJlpgw runId 4!
2018-05-04T11:41:45    DEBUG - Writing current task info to /builds/scriptworker/work/current_task_info.json...
2018-05-04T11:41:45    DEBUG - pushapk MTp5zddYQOGnoxBdnJlpgw is scriptworker
2018-05-04T11:41:45     INFO - build_task_dependencies pushapk MTp5zddYQOGnoxBdnJlpgw
2018-05-04T11:41:45     INFO - find_sorted_task_dependencies pushapk MTp5zddYQOGnoxBdnJlpgw
2018-05-04T11:41:45     INFO - found dependencies: [('pushapk:parent', 'Tfg02TJaSa6RNRaaS5l21g'), ('pushapk:signing', 'NdtSwD3pTEyFJ2lR2uW8Hw')]
2018-05-04T11:41:45    DEBUG - waiting 300 seconds before reclaiming...
2018-05-04T11:41:45    DEBUG - pushapk:parent Tfg02TJaSa6RNRaaS5l21g is docker-worker
2018-05-04T11:41:45    DEBUG - makedirs(/builds/scriptworker/work/cot/Tfg02TJaSa6RNRaaS5l21g)
2018-05-04T11:41:45     INFO - build_task_dependencies pushapk:parent Tfg02TJaSa6RNRaaS5l21g
2018-05-04T11:41:45     INFO - find_sorted_task_dependencies pushapk:parent Tfg02TJaSa6RNRaaS5l21g
2018-05-04T11:41:45     INFO - found dependencies: [('pushapk:parent:decision', 'Tfg02TJaSa6RNRaaS5l21g')]
2018-05-04T11:41:45    DEBUG - pushapk:signing NdtSwD3pTEyFJ2lR2uW8Hw is scriptworker
2018-05-04T11:41:45    DEBUG - makedirs(/builds/scriptworker/work/cot/NdtSwD3pTEyFJ2lR2uW8Hw)
2018-05-04T11:41:45     INFO - build_task_dependencies pushapk:signing NdtSwD3pTEyFJ2lR2uW8Hw
2018-05-04T11:41:45     INFO - find_sorted_task_dependencies pushapk:signing NdtSwD3pTEyFJ2lR2uW8Hw
2018-05-04T11:41:45     INFO - found dependencies: [('pushapk:signing:parent', 'Tfg02TJaSa6RNRaaS5l21g'), ('pushapk:signing:build', 'Kyin-SOGRQeHPDPknRECXA')]
2018-05-04T11:41:46    DEBUG - pushapk:signing:build Kyin-SOGRQeHPDPknRECXA is docker-worker
2018-05-04T11:41:46    DEBUG - makedirs(/builds/scriptworker/work/cot/Kyin-SOGRQeHPDPknRECXA)
2018-05-04T11:41:46     INFO - build_task_dependencies pushapk:signing:build Kyin-SOGRQeHPDPknRECXA
2018-05-04T11:41:46     INFO - find_sorted_task_dependencies pushapk:signing:build Kyin-SOGRQeHPDPknRECXA
2018-05-04T11:41:46     INFO - found dependencies: [('pushapk:signing:build:parent', 'Tfg02TJaSa6RNRaaS5l21g')]
2018-05-04T11:41:46    DEBUG - retry_async: Calling <function download_file at 0x7f3af67bf378>, attempt 1
2018-05-04T11:41:46     INFO - Downloading https://queue.taskcluster.net/v1/task/Tfg02TJaSa6RNRaaS5l21g/artifacts/public%2FchainOfTrust.json.asc
2018-05-04T11:41:46    DEBUG - retry_async: Calling <function download_file at 0x7f3af67bf378>, attempt 1
2018-05-04T11:41:46     INFO - Downloading https://queue.taskcluster.net/v1/task/NdtSwD3pTEyFJ2lR2uW8Hw/artifacts/public%2FchainOfTrust.json.asc
2018-05-04T11:41:46    DEBUG - retry_async: Calling <function download_file at 0x7f3af67bf378>, attempt 1
2018-05-04T11:41:46     INFO - Downloading https://queue.taskcluster.net/v1/task/Kyin-SOGRQeHPDPknRECXA/artifacts/public%2FchainOfTrust.json.asc
2018-05-04T11:41:46    DEBUG - makedirs(/builds/scriptworker/work/cot/Tfg02TJaSa6RNRaaS5l21g/public)
2018-05-04T11:41:46     INFO - Done
2018-05-04T11:41:47    DEBUG - makedirs(/builds/scriptworker/work/cot/Kyin-SOGRQeHPDPknRECXA/public)
2018-05-04T11:41:47     INFO - Done
2018-05-04T11:41:47    DEBUG - makedirs(/builds/scriptworker/work/cot/NdtSwD3pTEyFJ2lR2uW8Hw/public)
2018-05-04T11:41:47     INFO - Done
2018-05-04T11:41:47    DEBUG - /builds/scriptworker/work/cot/Tfg02TJaSa6RNRaaS5l21g/public/chainOfTrust.json.asc downloaded; hash is 9bde41fc67fd8accecbf22da9b93f2b0eeb4a7970ea275f1e9c3684dbd8212b0
2018-05-04T11:41:47    DEBUG - /builds/scriptworker/work/cot/NdtSwD3pTEyFJ2lR2uW8Hw/public/chainOfTrust.json.asc downloaded; hash is 578937f8047e699d3333c7cafb23bffcc1392f947420640966d1b71b10001a1e
2018-05-04T11:41:47    DEBUG - /builds/scriptworker/work/cot/Kyin-SOGRQeHPDPknRECXA/public/chainOfTrust.json.asc downloaded; hash is c721d896fa39a2b6a67857397e0690c8b50809aa2ec7cbf3cedf90cabcff6ef5
2018-05-04T11:41:47    DEBUG - Verifying the pushapk:parent Tfg02TJaSa6RNRaaS5l21g chain of trust signature against /builds/scriptworker/gpg/docker-worker
2018-05-04T11:41:47 CRITICAL - Fatal exception
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 124, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 99, in async_main
    await run_tasks(context)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 64, in run_tasks
    await verify_chain_of_trust(chain)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/cot/verify.py", line 1833, in verify_chain_of_trust
    verify_cot_signatures(chain)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/cot/verify.py", line 845, in verify_cot_signatures
    contents = fh.read()
  File "/tools/python35/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 3280: ordinal not in range(128)
2018-05-04T11:41:49     INFO - Scriptworker starting up at 2018-05-04 11:41:49+00:00 UTC
2018-05-04T11:41:49    DEBUG - rm(/builds/scriptworker/work)
2018-05-04T11:41:49    DEBUG - makedirs(/builds/scriptworker/work)
2018-05-04T11:41:49    DEBUG - rm(/builds/scriptworker/artifacts)
2018-05-04T11:41:49    DEBUG - makedirs(/builds/scriptworker/artifacts)
2018-05-04T11:41:49    DEBUG - makedirs(/builds/scriptworker/artifacts/public/logs)
2018-05-04T11:41:49    DEBUG - Calling claimWork...
2018-05-04T11:42:20    DEBUG - Calling claimWork...
```

**Comment by JohanLorenzo** [comment]
The root cause of this issue is filed in #216

**Comment by escapewindow** [comment]
The "starting up" line suggests that this crashes scriptworker.

**Comment by escapewindow** [comment]
Since the lack of log is due to a scriptworker crash, let's track this in #216.
