### ISSUE TITLE
CoT regression on Firefox Focus: Cannot download HG pushlog

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#277]
2 days ago, scriptworker 17.0.0 was deployed to all workers (https://github.com/mozilla-releng/build-puppet/pull/311), including the mobile ones. This caused [this CoT regression](https://tools.taskcluster.net/groups/YDFdZBm_QuC5ENF0uNIFyA/tasks/d-gkFlVKQSW0cJDzF0x-LQ/runs/1/logs/public%2Flogs%2Fchain_of_trust.log#L125) on Focus Nightly:

```
2018-11-29T14:08:16  WARNING - retry_async: download_file: too many retries!
2018-11-29T14:08:16 CRITICAL - Chain of Trust verification error!
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 1406, in verify_parent_task
    await verify_parent_task_definition(chain, link)
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 1266, in verify_parent_task_definition
    chain, parent_link, decision_link, tasks_for
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 1232, in get_jsone_context_and_template
    chain, parent_link, decision_link, tasks_for
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 1126, in populate_jsone_context
    await _get_additional_cron_jsone_context(parent_link, decision_link)
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 1059, in _get_additional_cron_jsone_context
    pushinfo = await _get_additional_hgpush_info(decision_link)
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 994, in _get_additional_hgpush_info
    pushlog_info = await get_pushlog_info(decision_link)
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/cot/verify.py", line 950, in get_pushlog_info
    context, pushlog_url, file_path, overwrite=False
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/utils.py", line 547, in load_json_or_yaml_from_url
    retry_exceptions=(DownloadError, aiohttp.ClientError),
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/utils.py", line 260, in retry_async
    return await func(*args, **kwargs)
  File "/builds/scriptworker/lib/python3.6/site-packages/scriptworker/utils.py", line 491, in download_file
    raise DownloadError("{} status {} is not 200!".format(loggable_url, resp.status))
scriptworker.exceptions.DownloadError: https://github.com/mozilla-mobile/focus-android/json-pushes?changeset=e841d1a5356053f1618931185f8411f0dadf4852&tipsonly=1&version=2&full=1 status 404 is not 200!

```

scriptworker 17.0.0 embeds https://github.com/mozilla-releng/scriptworker/pull/253 which changed when the hg push log is fetched. cc @Callek @escapewindow 

This breaks android-components, Firefox focus, and the current work on reference-browser. cc @MihaiTabara @mitchhentges 

As a temporary fix, I rolled back scriptworker 16.2.1 just to make focus nightly go through. I'm on the fix.

**Comment by JohanLorenzo** [comment]
Fixed by #278

**Comment by escapewindow** [comment]
I wonder if we should either rename the `_get_additional_*_jsone_context` functions to include `firefox`, or if they should handle the various `cot_product`s.

**Comment by JohanLorenzo** [comment]
@escapewindow Done in #284. I named `_get_additional_*_jsone_context()` `_get_additional_hg_*_jsone_context` because comms also needs these functions. Please let me know what you think of it.
