### ISSUE TITLE
upload_artifacts stackdump

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#34]
On signing-linux-1, at 2016-12-02T17:31:40 UTC, we appear to have hit a fatal issue in `upload_artifacts`:

```
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/connector.py", line 608, in _create_d
irect_connection
    local_addr=self._local_addr)
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 713, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 736, in _create_connection_transport
    yield from waiter
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/connector.py", line 306, in connect
    yield from self._create_connection(req)
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/connector.py", line 585, in _create_c
onnection
    transport, proto = yield from self._create_direct_connection(req)
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/connector.py", line 631, in _create_d
irect_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno None] Can not connect to taskcluster-public-artifacts.s3-us-west-2.amazonaws.com:443 [None]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 101, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 82, in async_main
    await run_loop(context)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 59, in run_loop
    await upload_artifacts(context)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py", line 307, in upload_ar
tifacts
    await raise_future_exceptions(tasks)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 275, in raise_fu
ture_exceptions
    raise exc
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py", line 269, in retry_cre
ate_artifact
    kwargs=kwargs
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/utils.py", line 205, in retry_as
ync
    return await func(*args, **kwargs)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/task.py", line 242, in create_ar
tifact
    skip_auto_headers=skip_auto_headers, compress=False
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/client.py", line 558, in __aenter__
    self._resp = yield from self._coro
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/client.py", line 201, in _request
    conn = yield from self._connector.connect(req)
  File "/builds/scriptworker/lib/python3.5/site-packages/aiohttp/connector.py", line 316, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno None] Cannot connect to host taskcluster-public-artifacts.s3-us-west-2.amazonaws.com:443 ssl:True [Can not connect to taskcluster-public-artifacts.s3-us-west-2.amazonaws.com:443 [None]]
```

The try/except should probably catch `aiohttp.errors.DisconnectedError` and `ClientError` as well.

**Comment by escapewindow** [comment]
Fixed by #37.
