### ISSUE TITLE
gpg homedirs part N

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#39]
```
2016-12-09T02:50:05    DEBUG - scriptworker: lockfile /builds/scriptworker/.gpg_homedirs.lock exists: ready
2016-12-09T02:50:05     INFO - overwrite_gpg_home: /builds/scriptworker/gpg.tmp to /builds/scriptworker/gpg
2016-12-09T02:50:05     INFO - Backing up /builds/scriptworker/gpg to /builds/scriptworker/gpg.old
2016-12-09T02:50:05    DEBUG - makedirs(/builds/scriptworker/gpg)
2016-12-09T02:50:05 CRITICAL - Fatal exception
Traceback (most recent call last):
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 111, in main
    loop.run_until_complete(async_main(context))
  File "/tools/python35/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/tools/python35/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/tools/python35/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/worker.py", line 92, in async_main
    overwrite_gpg_home(tmp_gpg_home, context.config['base_gpg_home_dir'])
  File "/builds/scriptworker/lib/python3.5/site-packages/scriptworker/gpg.py", line 1023, in overwrite_gpg_home
    os.path.join(real_gpg_home, filepath)
FileNotFoundError: [Errno 2] No such file or directory: '/builds/scriptworker/gpg.tmp/docker-worker/trustdb.gpg' -> '/builds/scriptworker/gpg/docker-worker/trustdb.gpg'
```

I've had the best luck with just

```
rm -rf /builds/scriptworker/gpg
mv /builds/scriptworker/gpg.tmp /builds/scriptworker/gpg
```

rather than trying to os.walk the dir and copy each file... maybe let's do that?

**Comment by escapewindow** [comment]
I see.  The problem is I'm calling `overwrite_gpg_home` on `/builds/scriptworker/gpg.tmp`, rather than individually on `/builds/scriptworker/gpg.tmp/docker-worker`, ...

Still, the nuke;mv seems most straightforward.
