### ISSUE TITLE
CoT intermittently fails to connect to Github

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/scriptworker#419]
It's a recurrent issue that occurs in most android-component releases. The latest occurrence is:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/scriptworker/worker.py", line 55, in do_run_task
    await run_cancellable(verify_chain_of_trust(chain))
  File "/app/lib/python3.7/site-packages/scriptworker/worker.py", line 158, in _run_cancellable
    result = await self.future
  File "/app/lib/python3.7/site-packages/scriptworker/cot/verify.py", line 2078, in verify_chain_of_trust
    await trace_back_to_tree(chain)
  File "/app/lib/python3.7/site-packages/scriptworker/cot/verify.py", line 2024, in trace_back_to_tree
    if restricted_privs and await chain.is_try_or_pull_request():
  File "/app/lib/python3.7/site-packages/scriptworker/cot/verify.py", line 143, in is_try_or_pull_request
    conditions = await raise_future_exceptions(tasks)
  File "/app/lib/python3.7/site-packages/scriptworker/utils.py", line 354, in raise_future_exceptions
    succeeded_results, _ = await _process_future_exceptions(tasks, raise_at_first_error=True)
  File "/app/lib/python3.7/site-packages/scriptworker/utils.py", line 388, in _process_future_exceptions
    raise exc
  File "/app/lib/python3.7/site-packages/scriptworker/cot/verify.py", line 268, in is_try_or_pull_request
    return await is_try_or_pull_request(self.context, self.task)
  File "/app/lib/python3.7/site-packages/scriptworker/task.py", line 494, in is_try_or_pull_request
    return await is_pull_request(context, task)
  File "/app/lib/python3.7/site-packages/scriptworker/task.py", line 474, in is_pull_request
    github_repository = GitHubRepository(repo_owner, repo_name, context.config['github_oauth_token'])
  File "/app/lib/python3.7/site-packages/scriptworker/github.py", line 38, in __init__
    self._github_repository = GitHub(token=token).repository(owner, repo_name)
  File "/app/lib/python3.7/site-packages/github3/github.py", line 1981, in repository
    json = self._json(self._get(url), 200)
  File "/app/lib/python3.7/site-packages/github3/models.py", line 211, in _get
    return self._request("get", url, **kwargs)
  File "/app/lib/python3.7/site-packages/github3/models.py", line 201, in _request
    raise exceptions.ConnectionError(exc)
github3.exceptions.ConnectionError: <class 'requests.exceptions.ConnectTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla-mobile/android-components (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb000aa9690>, 'Connection to api.github.com timed out. (connect timeout=4)'))
```

https://firefox-ci-tc.services.mozilla.com/tasks/DxrlM5kfTwihwmFMALOH9g/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FDxrlM5kfTwihwmFMALOH9g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Fchain_of_trust.log#L355

**Comment by JohanLorenzo** [comment]
cc @MihaiTabara @pocmo
