### ISSUE TITLE
scriptworker no longer runs (typing)

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/scriptworker#496]
CC @Callek 

When I run scriptworker locally, I get

```
(swenv) akimoz: ~/src/releng/scriptworker-scripts/githubscript (master) [12:19:44]
10095$ scriptworker --help
Traceback (most recent call last):
  File "/Users/asasaki/.pyenv/versions/swenv/bin/scriptworker", line 11, in <module>
    load_entry_point('scriptworker', 'console_scripts', 'scriptworker')()
  File "/Users/asasaki/.pyenv/versions/3.8.0/envs/swenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/asasaki/.pyenv/versions/3.8.0/envs/swenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/asasaki/.pyenv/versions/3.8.0/envs/swenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/asasaki/.pyenv/versions/3.8.0/envs/swenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/asasaki/src/tc/scriptworker/src/scriptworker/worker.py", line 20, in <module>
    from scriptworker.artifacts import upload_artifacts
  File "/Users/asasaki/src/tc/scriptworker/src/scriptworker/artifacts.py", line 18, in <module>
    from scriptworker.client import validate_artifact_url
  File "/Users/asasaki/src/tc/scriptworker/src/scriptworker/client.py", line 23, in <module>
    from scriptworker.constants import STATUSES
  File "/Users/asasaki/src/tc/scriptworker/src/scriptworker/constants.py", line 34, in <module>
    DEFAULT_CONFIG: immutabledict[str, Any] = immutabledict(
TypeError: 'ABCMeta' object is not subscriptable
```

We need to fix, or back out the mypy changes.

**Comment by Callek** [comment]
bah, this should have worked fine in 3.7+ with an appropriately new `immuteabledict` -- lets just disable mypy for now and back out, (I'm not a huge fan of how immuteabledict did this).

My time is short this week, and you need this repo able to accept changes at any point.

**Comment by escapewindow** [comment]
Ah, my immutabledict is old. Maybe we just need to update requirements with `immutabledict>=1.3.0`.
